package org.youthnet.debug.domain.core.old;
// Generated 14-Dec-2009 11:46:32 by Hibernate Tools 3.2.2.GA


import org.hibernate.annotations.Type;
import org.youthnet.debug.domain.common.UuidType;
import org.youthnet.debug.domain.core.GenericDTO;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VBase3Preference generated by hbm2java
 */
@Entity
@Table(name = "VBase3Preference")
public class VBase3Preference extends GenericDTO implements java.io.Serializable {


    private UuidType languageId;
    private boolean usingVisualNotification;
    private boolean usingAudioNotification;
    private boolean usingLogNotification;
    private Integer dataSchemaVersion;
    private String applicationName;
    private String copyright;
    private Integer colourTheme;
    private UuidType defaultCountyId;
    private UuidType defaultCountryId;
    private boolean useDefaultCounty;
    private boolean useDefaultCountry;

    public VBase3Preference() {
    }

    public VBase3Preference(UuidType languageId, boolean usingVisualNotification, boolean usingAudioNotification, boolean usingLogNotification, Integer dataSchemaVersion, String applicationName, String copyright, Integer colourTheme, UuidType defaultCountyId, UuidType defaultCountryId, boolean useDefaultCounty, boolean useDefaultCountry) {
        this.languageId = languageId;
        this.usingVisualNotification = usingVisualNotification;
        this.usingAudioNotification = usingAudioNotification;
        this.usingLogNotification = usingLogNotification;
        this.dataSchemaVersion = dataSchemaVersion;
        this.applicationName = applicationName;
        this.copyright = copyright;
        this.colourTheme = colourTheme;
        this.defaultCountyId = defaultCountyId;
        this.defaultCountryId = defaultCountryId;
        this.useDefaultCounty = useDefaultCounty;
        this.useDefaultCountry = useDefaultCountry;
    }

    @Column(columnDefinition = "raw(16)")
    @Type(type = "org.youthnet.debug.domain.common.impl.UuidTypeImpl")
    public UuidType getLanguageId() {
        return this.languageId;
    }

    public void setLanguageId(UuidType languageId) {
        this.languageId = languageId;
    }

    @Column
    public boolean isUsingVisualNotification() {
        return this.usingVisualNotification;
    }

    public void setUsingVisualNotification(boolean usingVisualNotification) {
        this.usingVisualNotification = usingVisualNotification;
    }

    @Column
    public boolean isUsingAudioNotification() {
        return this.usingAudioNotification;
    }

    public void setUsingAudioNotification(boolean usingAudioNotification) {
        this.usingAudioNotification = usingAudioNotification;
    }

    @Column
    public boolean isUsingLogNotification() {
        return this.usingLogNotification;
    }

    public void setUsingLogNotification(boolean usingLogNotification) {
        this.usingLogNotification = usingLogNotification;
    }

    @Column
    public Integer getDataSchemaVersion() {
        return this.dataSchemaVersion;
    }

    public void setDataSchemaVersion(Integer dataSchemaVersion) {
        this.dataSchemaVersion = dataSchemaVersion;
    }

    @Column
    public String getApplicationName() {
        return this.applicationName;
    }

    public void setApplicationName(String applicationName) {
        this.applicationName = applicationName;
    }

    @Column
    public String getCopyright() {
        return this.copyright;
    }

    public void setCopyright(String copyright) {
        this.copyright = copyright;
    }

    @Column
    public Integer getColourTheme() {
        return this.colourTheme;
    }

    public void setColourTheme(Integer colourTheme) {
        this.colourTheme = colourTheme;
    }

    @Column(columnDefinition = "raw(16)")
    @Type(type = "org.youthnet.debug.domain.common.impl.UuidTypeImpl")
    public UuidType getDefaultCountyId() {
        return this.defaultCountyId;
    }

    public void setDefaultCountyId(UuidType defaultCountyId) {
        this.defaultCountyId = defaultCountyId;
    }

    @Column(columnDefinition = "raw(16)")
    @Type(type = "org.youthnet.debug.domain.common.impl.UuidTypeImpl")
    public UuidType getDefaultCountryId() {
        return this.defaultCountryId;
    }

    public void setDefaultCountryId(UuidType defaultCountryId) {
        this.defaultCountryId = defaultCountryId;
    }

    @Column
    public boolean isUseDefaultCounty() {
        return this.useDefaultCounty;
    }

    public void setUseDefaultCounty(boolean useDefaultCounty) {
        this.useDefaultCounty = useDefaultCounty;
    }

    @Column
    public boolean isUseDefaultCountry() {
        return this.useDefaultCountry;
    }

    public void setUseDefaultCountry(boolean useDefaultCountry) {
        this.useDefaultCountry = useDefaultCountry;
    }


}


