package org.youthnet.debug.domain.core.old;
// Generated 14-Dec-2009 11:46:32 by Hibernate Tools 3.2.2.GA


import org.youthnet.debug.domain.core.GenericDTO;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ViewsTable generated by hbm2java
 */
@Entity
@Table(name = "ViewsTable")
public class ViewsTable extends GenericDTO implements java.io.Serializable {


    private Integer vbase2Id;
    private String fieldName;
    private String sectionName;
    private String sectionLookup;
    private String lookupUpTypesValue;
    private String discriminator;
    private boolean isSKills;
    private String skillType;

    public ViewsTable() {
    }

    public ViewsTable(Integer vbase2Id, String fieldName, String sectionName, String sectionLookup, String lookupUpTypesValue, String discriminator, boolean isSKills, String skillType) {
        this.vbase2Id = vbase2Id;
        this.fieldName = fieldName;
        this.sectionName = sectionName;
        this.sectionLookup = sectionLookup;
        this.lookupUpTypesValue = lookupUpTypesValue;
        this.discriminator = discriminator;
        this.isSKills = isSKills;
        this.skillType = skillType;
    }

    @Column
    public Integer getVbase2Id() {
        return this.vbase2Id;
    }

    public void setVbase2Id(Integer vbase2Id) {
        this.vbase2Id = vbase2Id;
    }

    @Column
    public String getFieldName() {
        return this.fieldName;
    }

    public void setFieldName(String fieldName) {
        this.fieldName = fieldName;
    }

    @Column
    public String getSectionName() {
        return this.sectionName;
    }

    public void setSectionName(String sectionName) {
        this.sectionName = sectionName;
    }

    @Column
    public String getSectionLookup() {
        return this.sectionLookup;
    }

    public void setSectionLookup(String sectionLookup) {
        this.sectionLookup = sectionLookup;
    }

    @Column
    public String getLookupUpTypesValue() {
        return this.lookupUpTypesValue;
    }

    public void setLookupUpTypesValue(String lookupUpTypesValue) {
        this.lookupUpTypesValue = lookupUpTypesValue;
    }

    @Column
    public String getDiscriminator() {
        return this.discriminator;
    }

    public void setDiscriminator(String discriminator) {
        this.discriminator = discriminator;
    }

    @Column
    public boolean isIsSKills() {
        return this.isSKills;
    }

    public void setIsSKills(boolean isSKills) {
        this.isSKills = isSKills;
    }

    @Column
    public String getSkillType() {
        return this.skillType;
    }

    public void setSkillType(String skillType) {
        this.skillType = skillType;
    }


}


