package org.youthnet.debug.domain.core.old;
// Generated 14-Dec-2009 11:46:32 by Hibernate Tools 3.2.2.GA


import org.hibernate.annotations.*;
import org.youthnet.debug.domain.core.lookups.TelephoneType;

import javax.persistence.*;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VolunteerContactTelephone generated by hbm2java
 */
@Entity
@Table(name = "VolunteerContactTelephones")
@PrimaryKeyJoinColumn(name = "VolunteerContactInfoId", columnDefinition = "raw(16)")
public class VolunteerContactTelephone extends VolunteerContactInfo implements java.io.Serializable {


private Volunteer contactDetails;
private TelephoneType type;
private String number;

    public VolunteerContactTelephone() {
    }

	
    public VolunteerContactTelephone(String number) {
        this.number = number;
    }
    public VolunteerContactTelephone(boolean isActive, boolean isDefault, String notes, Volunteer contactDetails, TelephoneType type, String number) {
        super(isActive, isDefault, notes);        
       this.contactDetails = contactDetails;
       this.type = type;
       this.number = number;
    }

    @ManyToOne(targetEntity = Volunteer.class,
            fetch = FetchType.EAGER)
    @Cascade(org.hibernate.annotations.CascadeType.SAVE_UPDATE)
    @JoinColumn(name = "VolunteerId", columnDefinition = "raw(16)")
    @javax.xml.bind.annotation.XmlTransient
    public Volunteer getContactDetails() {
        return this.contactDetails;
    }

    public void setContactDetails(Volunteer contactDetails) {
        this.contactDetails = contactDetails;
    }

    @ManyToOne(targetEntity = TelephoneType.class,
            fetch = FetchType.EAGER)
    @JoinColumn(name = "TelephoneTypeId", columnDefinition = "raw(16)")
    public TelephoneType getType() {
        return this.type;
    }

    public void setType(TelephoneType type) {
        this.type = type;
    }

    @Column(length = 255, nullable = false, name = "tel_number")
    public String getNumber() {
        return this.number;
    }

    public void setNumber(String number) {
        this.number = number;
    }




}


