package org.youthnet.debug.domain.core;
// Generated 14-Dec-2009 11:46:32 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.ForeignKey;
import org.youthnet.debug.domain.core.lookups.ActivityType;

import javax.persistence.*;
import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ActivityLog generated by hbm2java
 */
@Entity
@Table(name = "ActivityLogs")
public class ActivityLog extends GenericDTO implements java.io.Serializable {

    @Column
    private Integer vbase2Id;

    @Column
    private Date startDate;

    @Column
    private Date endDate;

    @Column
    private boolean isAllDayEvent;

    @Column
    private boolean showInCalender;

    @Column(length = 5)
    private String startTime;

    @Column(length = 5)
    private String endTime;

    @Column(length = 255)
    private String subject;

    @Column
    private String notes;

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "ActivityTypeId", columnDefinition = "raw(16)")
    private ActivityType activityType;

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "PersonHereId", columnDefinition = "raw(16)")
    private OrganisationContact personHere;

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.EAGER)
    @Fetch(value = org.hibernate.annotations.FetchMode.SUBSELECT)
    @ForeignKey(name = "FK_VolunteerActivityLogs")
    @JoinColumn(name = "ActivityLogId", columnDefinition = "raw(16)")
    private Set<VolunteerActivityLog> volunteerActivityLogs = new HashSet<VolunteerActivityLog>(0);

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.EAGER)
    @Fetch(value = org.hibernate.annotations.FetchMode.SUBSELECT)
    @ForeignKey(name = "FK_OrganisationActivityLogs")
    @JoinColumn(name = "ActivityLogId", columnDefinition = "raw(16)")
    private Set<OrganisationActivityLog> organisationActivityLogs = new HashSet<OrganisationActivityLog>(0);

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.EAGER)
    @Fetch(value = org.hibernate.annotations.FetchMode.SUBSELECT)
    @ForeignKey(name = "FK_OpportunityActivityLogs")
    @JoinColumn(name = "ActivityLogId", columnDefinition = "raw(16)")
    private Set<OpportunityActivityLog> opportunityActivityLogs = new HashSet<OpportunityActivityLog>(0);

    public ActivityLog() {
    }

    public ActivityLog(Integer vbase2Id, Date startDate, Date endDate, boolean isAllDayEvent, boolean showInCalender, String startTime, String endTime, String subject, String notes, ActivityType activityType, OrganisationContact personHere, Set<VolunteerActivityLog> volunteerActivityLogs, Set<OrganisationActivityLog> organisationActivityLogs, Set<OpportunityActivityLog> opportunityActivityLogs) {
        this.vbase2Id = vbase2Id;
        this.startDate = startDate;
        this.endDate = endDate;
        this.isAllDayEvent = isAllDayEvent;
        this.showInCalender = showInCalender;
        this.startTime = startTime;
        this.endTime = endTime;
        this.subject = subject;
        this.notes = notes;
        this.activityType = activityType;
        this.personHere = personHere;
        this.volunteerActivityLogs = volunteerActivityLogs;
        this.organisationActivityLogs = organisationActivityLogs;
        this.opportunityActivityLogs = opportunityActivityLogs;
    }

    public Integer getVbase2Id() {
        return this.vbase2Id;
    }

    public void setVbase2Id(Integer vbase2Id) {
        this.vbase2Id = vbase2Id;
    }

    public Date getStartDate() {
        return this.startDate;
    }

    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    public Date getEndDate() {
        return this.endDate;
    }

    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    public boolean isIsAllDayEvent() {
        return this.isAllDayEvent;
    }

    public void setIsAllDayEvent(boolean isAllDayEvent) {
        this.isAllDayEvent = isAllDayEvent;
    }

    public boolean isShowInCalender() {
        return this.showInCalender;
    }

    public void setShowInCalender(boolean showInCalender) {
        this.showInCalender = showInCalender;
    }

    public String getStartTime() {
        return this.startTime;
    }

    public void setStartTime(String startTime) {
        this.startTime = startTime;
    }

    public String getEndTime() {
        return this.endTime;
    }

    public void setEndTime(String endTime) {
        this.endTime = endTime;
    }

    public String getSubject() {
        return this.subject;
    }

    public void setSubject(String subject) {
        this.subject = subject;
    }

    public String getNotes() {
        return this.notes;
    }

    public void setNotes(String notes) {
        this.notes = notes;
    }

    public ActivityType getActivityType() {
        return this.activityType;
    }

    public void setActivityType(ActivityType activityType) {
        this.activityType = activityType;
    }

    public OrganisationContact getPersonHere() {
        return this.personHere;
    }

    public void setPersonHere(OrganisationContact personHere) {
        this.personHere = personHere;
    }

    public Set<VolunteerActivityLog> getVolunteerActivityLogs() {
        return this.volunteerActivityLogs;
    }

    public void setVolunteerActivityLogs(Set<VolunteerActivityLog> volunteerActivityLogs) {
        this.volunteerActivityLogs = volunteerActivityLogs;
    }

    public Set<OrganisationActivityLog> getOrganisationActivityLogs() {
        return this.organisationActivityLogs;
    }

    public void setOrganisationActivityLogs(Set<OrganisationActivityLog> organisationActivityLogs) {
        this.organisationActivityLogs = organisationActivityLogs;
    }

    public Set<OpportunityActivityLog> getOpportunityActivityLogs() {
        return this.opportunityActivityLogs;
    }

    public void setOpportunityActivityLogs(Set<OpportunityActivityLog> opportunityActivityLogs) {
        this.opportunityActivityLogs = opportunityActivityLogs;
    }


}


