package org.youthnet.debug.domain.core;
// Generated 14-Dec-2009 11:46:32 by Hibernate Tools 3.2.2.GA


import org.youthnet.debug.domain.core.GenericDTO;
import org.youthnet.debug.domain.core.lookups.Country;
import org.youthnet.debug.domain.core.lookups.County;

import javax.persistence.*;

/**
 * Address generated by hbm2java
 */
@Entity
@Table(name = "Addresses")
@Inheritance(strategy = InheritanceType.JOINED)
public class Address extends GenericDTO implements java.io.Serializable {

    @Column
    private Integer vbase2Id;

    @Column(length = 100)
    private String address1;

    @Column(length = 100)
    private String address2;

    @Column(length = 100)
    private String address3;

    @Column(length = 100)
    private String town;

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "CountyId", columnDefinition = "raw(16)")
    private County county;

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "CountryId", columnDefinition = "raw(16)")
    private Country country;

    @Column
    private String PostCode;

    @Column(length = 2000)
    private String Directions;

    public Address() {
    }

    public Address(Integer vbase2Id, String address1, String address2, String address3, String town, County county, Country country, String PostCode, String Directions) {
        this.vbase2Id = vbase2Id;
        this.address1 = address1;
        this.address2 = address2;
        this.address3 = address3;
        this.town = town;
        this.county = county;
        this.country = country;
        this.PostCode = PostCode;
        this.Directions = Directions;
    }

    public Integer getVbase2Id() {
        return this.vbase2Id;
    }

    public void setVbase2Id(Integer vbase2Id) {
        this.vbase2Id = vbase2Id;
    }

    public String getAddress1() {
        return this.address1;
    }

    public void setAddress1(String address1) {
        this.address1 = address1;
    }

    public String getAddress2() {
        return this.address2;
    }

    public void setAddress2(String address2) {
        this.address2 = address2;
    }

    public String getAddress3() {
        return this.address3;
    }

    public void setAddress3(String address3) {
        this.address3 = address3;
    }

    public String getTown() {
        return this.town;
    }

    public void setTown(String town) {
        this.town = town;
    }

    public County getCounty() {
        return this.county;
    }

    public void setCounty(County county) {
        this.county = county;
    }

    public Country getCountry() {
        return this.country;
    }

    public void setCountry(Country country) {
        this.country = country;
    }

    public String getPostCode() {
        return this.PostCode;
    }

    public void setPostCode(String PostCode) {
        this.PostCode = PostCode;
    }

    public String getDirections() {
        return this.Directions;
    }

    public void setDirections(String Directions) {
        this.Directions = Directions;
    }
}


