package org.youthnet.debug.domain.core;
// Generated 14-Dec-2009 11:46:32 by Hibernate Tools 3.2.2.GA


import org.youthnet.debug.domain.core.lookups.ArrangementStatus;
import org.youthnet.debug.domain.core.lookups.Arrangement;
import org.youthnet.debug.domain.core.PolicyEntry;

import javax.persistence.*;

/**
 * ArrangementsRecordEntry generated by hbm2java
 */
@Entity
@DiscriminatorValue(value = "A")
public class ArrangementsRecordEntry extends PolicyEntry implements java.io.Serializable {

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "PolicyId", columnDefinition = "raw(16)")
    private Arrangement policy;

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "PolicyStatusId", columnDefinition = "raw(16)")
    private ArrangementStatus policyStatus;

    public ArrangementsRecordEntry() {
    }

    public ArrangementsRecordEntry(Integer vbase2Id, String comments, Arrangement policy, ArrangementStatus policyStatus) {
        super(vbase2Id, comments);
        this.policy = policy;
        this.policyStatus = policyStatus;
    }

    public Arrangement getPolicy() {
        return this.policy;
    }

    public void setPolicy(Arrangement policy) {
        this.policy = policy;
    }

    public ArrangementStatus getPolicyStatus() {
        return this.policyStatus;
    }

    public void setPolicyStatus(ArrangementStatus policyStatus) {
        this.policyStatus = policyStatus;
    }


}


