package org.youthnet.debug.domain.core;
// Generated 14-Dec-2009 11:46:32 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import org.hibernate.annotations.*;
import org.youthnet.debug.domain.core.ArrangementsRecordEntry;
import org.youthnet.debug.domain.core.ContactDetails;
import org.youthnet.debug.domain.core.GenericDTO;
import org.youthnet.debug.domain.core.Organisation;
import org.youthnet.debug.domain.core.lookups.*;
import org.youthnet.debug.domain.core.lookups.CampaignsAndInitiatives;
import org.youthnet.debug.domain.core.lookups.CauseInterest;
import org.youthnet.debug.domain.core.lookups.SelectionMethod;
import org.youthnet.debug.domain.core.lookups.Skill;
import org.youthnet.debug.domain.core.lookups.Suitabilities;
import org.youthnet.debug.domain.core.lookups.TaggedData;
import org.youthnet.debug.domain.core.lookups.TypeOfActivity;
import org.youthnet.debug.domain.core.LocationBase;

import javax.persistence.*;
import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Opportunity generated by hbm2java
 */
@Entity
@Table(name = "Opportunities")
public class Opportunity extends GenericDTO implements java.io.Serializable {

    @Column
    private Integer vbase2Id;

    @Column(length = 255)
    @Index(name = "OppTitle")
    private String title;

    @Column(length = 150)
    @Index(name = "OppOwnId")
    private String ownId;

    @Column
    private boolean locationsPubliclyViewable;

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "OrganisationId", columnDefinition = "raw(16)")
    private Organisation organisationId;

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.EAGER)
    @Fetch(value = org.hibernate.annotations.FetchMode.SUBSELECT)
    @JoinColumn(name = "OpportunityLocationId", columnDefinition = "raw(16)")
    @javax.xml.bind.annotation.XmlElementWrapper
    private Set<LocationBase> locations = new HashSet<LocationBase>();

    @Column(name = "useSharedIntConDets")
    private boolean useSharedInternalContactDetails;

    @Column
    private boolean useSharedPublicContactDetails;

    @Column
    private boolean isSharedInternalContactPublic;

    @ManyToOne(cascade = CascadeType.ALL, fetch = FetchType.EAGER)
    @JoinColumn(name = "SharedInternalContactDetailsId", columnDefinition = "raw(16)")
    private ContactDetails sharedInternalContactDetails;

    @ManyToOne(cascade = CascadeType.ALL, fetch = FetchType.EAGER)
    @JoinColumn(name = "SharedPublicContactDetailsId", columnDefinition = "raw(16)")
    private ContactDetails sharedPublicContactDetails;

    @ManyToMany(cascade = CascadeType.ALL, fetch = FetchType.EAGER)
    @Fetch(value = org.hibernate.annotations.FetchMode.SUBSELECT)
    @JoinTable(name = "OpportunityArrPolicyEntry",
            joinColumns = @JoinColumn(name = "OpportunityId", columnDefinition = "raw(16)"),
            inverseJoinColumns = @JoinColumn(name = "PolicyId", columnDefinition = "raw(16)"))
    private Set<ArrangementsRecordEntry> arrangements = new HashSet<ArrangementsRecordEntry>();

    @Column(length = 2000)
    private String requirements;

    @Column(length = 2000)
    private String benefits;

    @ManyToMany(fetch = FetchType.EAGER)
    @Fetch(value = org.hibernate.annotations.FetchMode.SUBSELECT)
    @JoinTable(name = "OpportunitySkillsRequired",
            joinColumns = @JoinColumn(name = "OpportunityId", columnDefinition = "raw(16)"),
            inverseJoinColumns = @JoinColumn(name = "LookupId", columnDefinition = "raw(16)"))
    private Set<Skill> skillsRequired = new HashSet<Skill>();

    @ManyToMany(fetch = FetchType.EAGER)
    @Fetch(value = org.hibernate.annotations.FetchMode.SUBSELECT)
    @JoinTable(name = "OpportunitySkillsToGain",
            joinColumns = @JoinColumn(name = "OpportunityId", columnDefinition = "raw(16)"),
            inverseJoinColumns = @JoinColumn(name = "LookupId", columnDefinition = "raw(16)"))
    private Set<Skill> skillsToGain = new HashSet<Skill>();

    @Column(length = 2000)
    private String description;

    @Column(length = 250)
    private String shortDescription;

    @Column
    private float monetaryValuePerHour;

    @Column
    private boolean isVirtualRemote;

    @Column
    private boolean isResidential;

    @Column
    private boolean isOneOff;

    @Column
    private boolean isDateSpecific;

    @Column
    private Date specificStartDate;

    @Column
    private Date specificEndDate;

    @Column
    private long commitmentAm;

    @Column
    private long commitmentPm;

    @Column
    private long commitmentEve;

    @ManyToMany(fetch = FetchType.EAGER)
    @Fetch(value = org.hibernate.annotations.FetchMode.SUBSELECT)
    @JoinTable(name = "OpportunityCommitmentTypes",
            joinColumns = @JoinColumn(name = "OpportunityId", columnDefinition = "raw(16)"),
            inverseJoinColumns = @JoinColumn(name = "LookupId", columnDefinition = "raw(16)"))
    private Set<CommitmentType> commitmentTypes = new HashSet<CommitmentType>();

    @ManyToMany(fetch = FetchType.EAGER)
    @Fetch(value = org.hibernate.annotations.FetchMode.SUBSELECT)
    @JoinTable(name = "OpportunityTags",
            joinColumns = @JoinColumn(name = "OpportunityId", columnDefinition = "raw(16)"),
            inverseJoinColumns = @JoinColumn(name = "LookupId", columnDefinition = "raw(16)"))
    private Set<TaggedData> tags = new HashSet<TaggedData>();

    @ManyToMany(fetch = FetchType.EAGER)
    @Fetch(value = org.hibernate.annotations.FetchMode.SUBSELECT)
    @JoinTable(name = "OpportunityCampsAndInits",
            joinColumns = @JoinColumn(name = "OpportunityId", columnDefinition = "raw(16)"),
            inverseJoinColumns = @JoinColumn(name = "LookupId", columnDefinition = "raw(16)"))
    private Set<CampaignsAndInitiatives> campaignsAndInitiatives = new HashSet<CampaignsAndInitiatives>();

    @ManyToMany(fetch = FetchType.EAGER)
    @Fetch(value = org.hibernate.annotations.FetchMode.SUBSELECT)
    @JoinTable(name = "OpportunityTypesOfActivity",
            joinColumns = @JoinColumn(name = "OpportunityId", columnDefinition = "raw(16)"),
            inverseJoinColumns = @JoinColumn(name = "LookupId", columnDefinition = "raw(16)"))
    private Set<TypeOfActivity> typeOfActivity = new HashSet<TypeOfActivity>();

    @ManyToMany(fetch = FetchType.EAGER)
    @Fetch(value = org.hibernate.annotations.FetchMode.SUBSELECT)
    @JoinTable(name = "OpportunityCausesInterests",
            joinColumns = @JoinColumn(name = "OpportunityId", columnDefinition = "raw(16)"),
            inverseJoinColumns = @JoinColumn(name = "LookupId", columnDefinition = "raw(16)"))
    private Set<CauseInterest> causesInterests = new HashSet<CauseInterest>();

    @Column
    private Date advertisingStartDate;

    @Column
    private Date advertisingEndDate;

    @Column
    private boolean publishToDoIt;

    @Column
    private boolean isActive;

    @ManyToMany(fetch = FetchType.EAGER)
    @Fetch(value = org.hibernate.annotations.FetchMode.SUBSELECT)
    @JoinTable(name = "OpportunityAddSpecSuitabs",
            joinColumns = @JoinColumn(name = "OpportunityId", columnDefinition = "raw(16)"),
            inverseJoinColumns = @JoinColumn(name = "LookupId", columnDefinition = "raw(16)"))
    private Set<Suitabilities> addSpecSuitabilities = new HashSet<Suitabilities>(0);

    @ManyToMany(fetch = FetchType.EAGER)
    @Fetch(value = org.hibernate.annotations.FetchMode.SUBSELECT)
    @JoinTable(name = "OpportunitySelectionMethods",
            joinColumns = @JoinColumn(name = "OpportunityId", columnDefinition = "raw(16)"),
            inverseJoinColumns = @JoinColumn(name = "LookupId", columnDefinition = "raw(16)"))
    private Set<SelectionMethod> selectionMethods = new HashSet<SelectionMethod>(0);

    public Opportunity() {
    }

    public Opportunity(Integer vbase2Id, String title, String ownId, boolean locationsPubliclyViewable, Organisation organisationId, Set<LocationBase> locations, boolean useSharedInternalContactDetails, boolean useSharedPublicContactDetails, boolean isSharedInternalContactPublic, ContactDetails sharedInternalContactDetails, ContactDetails sharedPublicContactDetails, Set<ArrangementsRecordEntry> arrangements, String requirements, String benefits, Set<Skill> skillsRequired, Set<Skill> skillsToGain, String description, String shortDescription, float monetaryValuePerHour, boolean isVirtualRemote, boolean isResidential, boolean isOneOff, boolean isDateSpecific, Date specificStartDate, Date specificEndDate, long commitmentAm, long commitmentPm, long commitmentEve, Set<CommitmentType> commitmentTypes, Set<TaggedData> tags, Set<CampaignsAndInitiatives> campaignsAndInitiatives, Set<TypeOfActivity> typeOfActivity, Set<CauseInterest> causesInterests, Date advertisingStartDate, Date advertisingEndDate, boolean publishToDoIt, boolean isActive, Set<Suitabilities> addSpecSuitabilities, Set<SelectionMethod> selectionMethods) {
        this.vbase2Id = vbase2Id;
        this.title = title;
        this.ownId = ownId;
        this.locationsPubliclyViewable = locationsPubliclyViewable;
        this.organisationId = organisationId;
        this.locations = locations;
        this.useSharedInternalContactDetails = useSharedInternalContactDetails;
        this.useSharedPublicContactDetails = useSharedPublicContactDetails;
        this.isSharedInternalContactPublic = isSharedInternalContactPublic;
        this.sharedInternalContactDetails = sharedInternalContactDetails;
        this.sharedPublicContactDetails = sharedPublicContactDetails;
        this.arrangements = arrangements;
        this.requirements = requirements;
        this.benefits = benefits;
        this.skillsRequired = skillsRequired;
        this.skillsToGain = skillsToGain;
        this.description = description;
        this.shortDescription = shortDescription;
        this.monetaryValuePerHour = monetaryValuePerHour;
        this.isVirtualRemote = isVirtualRemote;
        this.isResidential = isResidential;
        this.isOneOff = isOneOff;
        this.isDateSpecific = isDateSpecific;
        this.specificStartDate = specificStartDate;
        this.specificEndDate = specificEndDate;
        this.commitmentAm = commitmentAm;
        this.commitmentPm = commitmentPm;
        this.commitmentEve = commitmentEve;
        this.commitmentTypes = commitmentTypes;
        this.tags = tags;
        this.campaignsAndInitiatives = campaignsAndInitiatives;
        this.typeOfActivity = typeOfActivity;
        this.causesInterests = causesInterests;
        this.advertisingStartDate = advertisingStartDate;
        this.advertisingEndDate = advertisingEndDate;
        this.publishToDoIt = publishToDoIt;
        this.isActive = isActive;
        this.addSpecSuitabilities = addSpecSuitabilities;
        this.selectionMethods = selectionMethods;
    }

    public Integer getVbase2Id() {
        return this.vbase2Id;
    }

    public void setVbase2Id(Integer vbase2Id) {
        this.vbase2Id = vbase2Id;
    }

    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getOwnId() {
        return this.ownId;
    }

    public void setOwnId(String ownId) {
        this.ownId = ownId;
    }

    public boolean isLocationsPubliclyViewable() {
        return this.locationsPubliclyViewable;
    }

    public void setLocationsPubliclyViewable(boolean locationsPubliclyViewable) {
        this.locationsPubliclyViewable = locationsPubliclyViewable;
    }

    public Organisation getOrganisationId() {
        return this.organisationId;
    }

    public void setOrganisationId(Organisation organisationId) {
        this.organisationId = organisationId;
    }

    public Set<LocationBase> getLocations() {
        return this.locations;
    }

    public void setLocations(Set<LocationBase> locations) {
        this.locations = locations;
    }

    public boolean isUseSharedInternalContactDetails() {
        return this.useSharedInternalContactDetails;
    }

    public void setUseSharedInternalContactDetails(boolean useSharedInternalContactDetails) {
        this.useSharedInternalContactDetails = useSharedInternalContactDetails;
    }

    public boolean isUseSharedPublicContactDetails() {
        return this.useSharedPublicContactDetails;
    }

    public void setUseSharedPublicContactDetails(boolean useSharedPublicContactDetails) {
        this.useSharedPublicContactDetails = useSharedPublicContactDetails;
    }

    public boolean isIsSharedInternalContactPublic() {
        return this.isSharedInternalContactPublic;
    }

    public void setIsSharedInternalContactPublic(boolean isSharedInternalContactPublic) {
        this.isSharedInternalContactPublic = isSharedInternalContactPublic;
    }

    public ContactDetails getSharedInternalContactDetails() {
        return this.sharedInternalContactDetails;
    }

    public void setSharedInternalContactDetails(ContactDetails sharedInternalContactDetails) {
        this.sharedInternalContactDetails = sharedInternalContactDetails;
    }

    public ContactDetails getSharedPublicContactDetails() {
        return this.sharedPublicContactDetails;
    }

    public void setSharedPublicContactDetails(ContactDetails sharedPublicContactDetails) {
        this.sharedPublicContactDetails = sharedPublicContactDetails;
    }

    public Set<ArrangementsRecordEntry> getArrangements() {
        return this.arrangements;
    }

    public void setArrangements(Set<ArrangementsRecordEntry> arrangements) {
        this.arrangements = arrangements;
    }

    public String getRequirements() {
        return this.requirements;
    }

    public void setRequirements(String requirements) {
        this.requirements = requirements;
    }

    public String getBenefits() {
        return this.benefits;
    }

    public void setBenefits(String benefits) {
        this.benefits = benefits;
    }

    public Set<Skill> getSkillsRequired() {
        return this.skillsRequired;
    }

    public void setSkillsRequired(Set<Skill> skillsRequired) {
        this.skillsRequired = skillsRequired;
    }

    public Set<Skill> getSkillsToGain() {
        return this.skillsToGain;
    }

    public void setSkillsToGain(Set<Skill> skillsToGain) {
        this.skillsToGain = skillsToGain;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getShortDescription() {
        return this.shortDescription;
    }

    public void setShortDescription(String shortDescription) {
        this.shortDescription = shortDescription;
    }

    public float getMonetaryValuePerHour() {
        return this.monetaryValuePerHour;
    }

    public void setMonetaryValuePerHour(float monetaryValuePerHour) {
        this.monetaryValuePerHour = monetaryValuePerHour;
    }

    public boolean isIsVirtualRemote() {
        return this.isVirtualRemote;
    }

    public void setIsVirtualRemote(boolean isVirtualRemote) {
        this.isVirtualRemote = isVirtualRemote;
    }

    public boolean isIsResidential() {
        return this.isResidential;
    }

    public void setIsResidential(boolean isResidential) {
        this.isResidential = isResidential;
    }

    public boolean isIsOneOff() {
        return this.isOneOff;
    }

    public void setIsOneOff(boolean isOneOff) {
        this.isOneOff = isOneOff;
    }

    public boolean isIsDateSpecific() {
        return this.isDateSpecific;
    }

    public void setIsDateSpecific(boolean isDateSpecific) {
        this.isDateSpecific = isDateSpecific;
    }

    public Date getSpecificStartDate() {
        return this.specificStartDate;
    }

    public void setSpecificStartDate(Date specificStartDate) {
        this.specificStartDate = specificStartDate;
    }

    public Date getSpecificEndDate() {
        return this.specificEndDate;
    }

    public void setSpecificEndDate(Date specificEndDate) {
        this.specificEndDate = specificEndDate;
    }

    public long getCommitmentAm() {
        return this.commitmentAm;
    }

    public void setCommitmentAm(long commitmentAm) {
        this.commitmentAm = commitmentAm;
    }

    public long getCommitmentPm() {
        return this.commitmentPm;
    }

    public void setCommitmentPm(long commitmentPm) {
        this.commitmentPm = commitmentPm;
    }

    public long getCommitmentEve() {
        return this.commitmentEve;
    }

    public void setCommitmentEve(long commitmentEve) {
        this.commitmentEve = commitmentEve;
    }

    public Set<CommitmentType> getCommitmentTypes() {
        return this.commitmentTypes;
    }

    public void setCommitmentTypes(Set<CommitmentType> commitmentTypes) {
        this.commitmentTypes = commitmentTypes;
    }

    public Set<TaggedData> getTags() {
        return this.tags;
    }

    public void setTags(Set<TaggedData> tags) {
        this.tags = tags;
    }

    public Set<CampaignsAndInitiatives> getCampaignsAndInitiatives() {
        return this.campaignsAndInitiatives;
    }

    public void setCampaignsAndInitiatives(Set<CampaignsAndInitiatives> campaignsAndInitiatives) {
        this.campaignsAndInitiatives = campaignsAndInitiatives;
    }

    public Set<TypeOfActivity> getTypeOfActivity() {
        return this.typeOfActivity;
    }

    public void setTypeOfActivity(Set<TypeOfActivity> typeOfActivity) {
        this.typeOfActivity = typeOfActivity;
    }

    public Set<CauseInterest> getCausesInterests() {
        return this.causesInterests;
    }

    public void setCausesInterests(Set<CauseInterest> causesInterests) {
        this.causesInterests = causesInterests;
    }

    public Date getAdvertisingStartDate() {
        return this.advertisingStartDate;
    }

    public void setAdvertisingStartDate(Date advertisingStartDate) {
        this.advertisingStartDate = advertisingStartDate;
    }

    public Date getAdvertisingEndDate() {
        return this.advertisingEndDate;
    }

    public void setAdvertisingEndDate(Date advertisingEndDate) {
        this.advertisingEndDate = advertisingEndDate;
    }

    public boolean isPublishToDoIt() {
        return this.publishToDoIt;
    }

    public void setPublishToDoIt(boolean publishToDoIt) {
        this.publishToDoIt = publishToDoIt;
    }

    public boolean isIsActive() {
        return this.isActive;
    }

    public void setIsActive(boolean isActive) {
        this.isActive = isActive;
    }

    public Set<Suitabilities> getAddSpecSuitabilities() {
        return this.addSpecSuitabilities;
    }

    public void setAddSpecSuitabilities(Set<Suitabilities> addSpecSuitabilities) {
        this.addSpecSuitabilities = addSpecSuitabilities;
    }

    public Set<SelectionMethod> getSelectionMethods() {
        return this.selectionMethods;
    }

    public void setSelectionMethods(Set<SelectionMethod> selectionMethods) {
        this.selectionMethods = selectionMethods;
    }
}


