package org.youthnet.debug.domain.core;
// Generated 14-Dec-2009 11:46:32 by Hibernate Tools 3.2.2.GA


import javax.persistence.*;

/**
 * OpportunityActivityLog generated by hbm2java
 */
@Entity
@Table(name = "OpportunityActLogs")
public class OpportunityActivityLog extends GenericDTO implements java.io.Serializable {

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "OpportunityId", columnDefinition = "raw(16)")
    private Opportunity opportunity;

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "ActivityLogId", columnDefinition = "raw(16)")
    @javax.xml.bind.annotation.XmlTransient
    private ActivityLog activityLog;

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "OpportunityLocationId", columnDefinition = "raw(16)")
    private LocationBase opportunityLocation;

    public OpportunityActivityLog() {
    }

    public OpportunityActivityLog(Opportunity opportunity, ActivityLog activityLog, LocationBase opportunityLocation) {
        this.opportunity = opportunity;
        this.activityLog = activityLog;
        this.opportunityLocation = opportunityLocation;
    }

    public Opportunity getOpportunity() {
        return this.opportunity;
    }

    public void setOpportunity(Opportunity opportunity) {
        this.opportunity = opportunity;
    }

    public ActivityLog getActivityLog() {
        return this.activityLog;
    }

    public void setActivityLog(ActivityLog activityLog) {
        this.activityLog = activityLog;
    }

    public LocationBase getOpportunityLocation() {
        return this.opportunityLocation;
    }

    public void setOpportunityLocation(LocationBase opportunityLocation) {
        this.opportunityLocation = opportunityLocation;
    }


}


