package org.youthnet.debug.domain.core;
// Generated 14-Dec-2009 11:46:32 by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;

import org.hibernate.annotations.Fetch;
import org.youthnet.debug.domain.core.Address;
import org.youthnet.debug.domain.core.Organisation;
import org.youthnet.debug.domain.core.lookups.Country;
import org.youthnet.debug.domain.core.lookups.County;
import org.youthnet.debug.domain.core.old.OrganisationContact;

import javax.persistence.*;

/**
 * OrganisationAddress generated by hbm2java
 */
@Entity
@Table(name = "OrganisationAddresses")
@PrimaryKeyJoinColumn(name = "AddressId", columnDefinition = "raw(16)")
public class OrganisationAddress extends Address implements java.io.Serializable {

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.EAGER)
    @Fetch(value = org.hibernate.annotations.FetchMode.SUBSELECT)
    @JoinColumn(name = "OrganisationAddressId")
    private Set<OrganisationContact> Contacts = new HashSet<OrganisationContact>();

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "OrgAddConInfoId", columnDefinition = "raw(16)")
    @javax.xml.bind.annotation.XmlTransient
    private Organisation OrganisationAddressInfo;

    @Column
    private String friendlyName;

    @Column
    private String organisationName;

    @Column
    private boolean useCustomOrganisationName;

    @Column
    private String email;

    @Column(name = "Telephone")
    private String tel;

    @Column
    private String emergencyTelephone;

    @Column
    private String fax;

    @Column
    private String website;

    @Column(length = 2000)
    private String directions;

    @Column
    private boolean isDefaultAddress;

    public OrganisationAddress() {
    }

    public OrganisationAddress(Integer vbase2Id, String address1, String address2, String address3, String town, County county, Country country, String PostCode, String Directions, Set<OrganisationContact> Contacts, Organisation OrganisationAddressInfo, String friendlyName, String organisationName, boolean useCustomOrganisationName, String email, String tel, String emergencyTelephone, String fax, String website, String directions, boolean isDefaultAddress) {
        super(vbase2Id, address1, address2, address3, town, county, country, PostCode, Directions);
        this.Contacts = Contacts;
        this.OrganisationAddressInfo = OrganisationAddressInfo;
        this.friendlyName = friendlyName;
        this.organisationName = organisationName;
        this.useCustomOrganisationName = useCustomOrganisationName;
        this.email = email;
        this.tel = tel;
        this.emergencyTelephone = emergencyTelephone;
        this.fax = fax;
        this.website = website;
        this.directions = directions;
        this.isDefaultAddress = isDefaultAddress;
    }

    public Set<OrganisationContact> getContacts() {
        return this.Contacts;
    }

    public void setContacts(Set<OrganisationContact> Contacts) {
        this.Contacts = Contacts;
    }

    public Organisation getOrganisationAddressInfo() {
        return this.OrganisationAddressInfo;
    }

    public void setOrganisationAddressInfo(Organisation OrganisationAddressInfo) {
        this.OrganisationAddressInfo = OrganisationAddressInfo;
    }

    public String getFriendlyName() {
        return this.friendlyName;
    }

    public void setFriendlyName(String friendlyName) {
        this.friendlyName = friendlyName;
    }

    public String getOrganisationName() {
        return this.organisationName;
    }

    public void setOrganisationName(String organisationName) {
        this.organisationName = organisationName;
    }

    public boolean isUseCustomOrganisationName() {
        return this.useCustomOrganisationName;
    }

    public void setUseCustomOrganisationName(boolean useCustomOrganisationName) {
        this.useCustomOrganisationName = useCustomOrganisationName;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getTel() {
        return this.tel;
    }

    public void setTel(String tel) {
        this.tel = tel;
    }

    public String getEmergencyTelephone() {
        return this.emergencyTelephone;
    }

    public void setEmergencyTelephone(String emergencyTelephone) {
        this.emergencyTelephone = emergencyTelephone;
    }

    public String getFax() {
        return this.fax;
    }

    public void setFax(String fax) {
        this.fax = fax;
    }

    public String getWebsite() {
        return this.website;
    }

    public void setWebsite(String website) {
        this.website = website;
    }

    public String getDirections() {
        return this.directions;
    }

    public void setDirections(String directions) {
        this.directions = directions;
    }

    public boolean isIsDefaultAddress() {
        return this.isDefaultAddress;
    }

    public void setIsDefaultAddress(boolean isDefaultAddress) {
        this.isDefaultAddress = isDefaultAddress;
    }
}


