package org.youthnet.debug.domain.core;
// Generated 14-Dec-2009 11:46:32 by Hibernate Tools 3.2.2.GA


import org.hibernate.annotations.Cascade;
import org.youthnet.debug.domain.core.lookups.Title;

import javax.persistence.*;

/**
 * OrganisationContact generated by hbm2java
 */
@Entity
@Table(name = "OrganisationContacts")
@PrimaryKeyJoinColumn(name = "ContactId", columnDefinition = "raw(16)")
public class OrganisationContact extends org.youthnet.debug.domain.core.Contact implements java.io.Serializable {


private OrganisationAddress organisationAddress;

    public OrganisationContact() {
    }

    public OrganisationContact(Integer vbase2Id, Title title, String firstName, String surname, String preferredName, String jobTitle, String department, String email, boolean usingAddressEmail, String tel, String fax, boolean usingAddressFax, boolean usingAddressTel, String mobile, String notes, boolean isActive, boolean useAsMainContact, OrganisationAddress organisationAddress) {
        super(vbase2Id, title, firstName, surname, preferredName, jobTitle, department, email, usingAddressEmail, tel, fax, usingAddressFax, usingAddressTel, mobile, notes, isActive, useAsMainContact);        
       this.organisationAddress = organisationAddress;
    }

    @ManyToOne(targetEntity = org.youthnet.debug.domain.core.OrganisationAddress.class,
            fetch = FetchType.EAGER)
    @Cascade(org.hibernate.annotations.CascadeType.SAVE_UPDATE)
    @JoinColumn(name = "OrganisationAddressId", columnDefinition = "raw(16)")
    @javax.xml.bind.annotation.XmlTransient
    public OrganisationAddress getOrganisationAddress() {
        return this.organisationAddress;
    }

    public void setOrganisationAddress(OrganisationAddress organisationAddress) {
        this.organisationAddress = organisationAddress;
    }
}


