package org.youthnet.debug.domain.core;
// Generated 14-Dec-2009 11:46:32 by Hibernate Tools 3.2.2.GA


import org.hibernate.annotations.Cascade;

import javax.persistence.*;

/**
 * OrganisationActivityLog generated by hbm2java
 */
@Entity
@Table(name = "OrganisationActivityLogs")
public class OrganisationActivityLog extends GenericDTO implements java.io.Serializable {


    private Organisation organisation;
    private OrganisationContact contact;
    private ActivityLog activityLog;

    public OrganisationActivityLog() {
    }

    public OrganisationActivityLog(Organisation organisation, OrganisationContact contact, ActivityLog activityLog) {
        this.organisation = organisation;
        this.contact = contact;
        this.activityLog = activityLog;
    }

    @ManyToOne(targetEntity = org.youthnet.debug.domain.core.Organisation.class,
            fetch = FetchType.EAGER)
    @Cascade(org.hibernate.annotations.CascadeType.SAVE_UPDATE)
    @JoinColumn(name = "OrganisationId", columnDefinition = "raw(16)")
    public Organisation getOrganisation() {
        return this.organisation;
    }

    public void setOrganisation(Organisation organisation) {
        this.organisation = organisation;
    }

    @ManyToOne(targetEntity = org.youthnet.debug.domain.core.OrganisationContact.class,
            fetch = FetchType.EAGER)
    @JoinColumn(name = "ContactId", columnDefinition = "raw(16)")
    public OrganisationContact getContact() {
        return this.contact;
    }

    public void setContact(OrganisationContact contact) {
        this.contact = contact;
    }

    @ManyToOne(targetEntity = org.youthnet.debug.domain.core.ActivityLog.class,
            fetch = FetchType.EAGER)
    @Cascade(org.hibernate.annotations.CascadeType.SAVE_UPDATE)
    @JoinColumn(name = "ActivityLogId", columnDefinition = "raw(16)")
    @javax.xml.bind.annotation.XmlTransient
    public ActivityLog getActivityLog() {
        return this.activityLog;
    }

    public void setActivityLog(ActivityLog activityLog) {
        this.activityLog = activityLog;
    }


}


