package org.youthnet.debug.domain.core;
// Generated 14-Dec-2009 11:46:32 by Hibernate Tools 3.2.2.GA


import javax.persistence.*;

/**
 * PolicyEntry generated by hbm2java
 */
@Entity
@Table(name = "PolicyEntries")
@Inheritance(strategy = InheritanceType.SINGLE_TABLE)
@DiscriminatorColumn(discriminatorType = DiscriminatorType.STRING,
        length = 1,
        name = "Discriminator")
public class PolicyEntry extends GenericDTO implements java.io.Serializable {


private Integer vbase2Id;
private String comments;

    public PolicyEntry() {
    }

    public PolicyEntry(Integer vbase2Id, String comments) {
       this.vbase2Id = vbase2Id;
       this.comments = comments;
    }

    @Column
    public Integer getVbase2Id() {
        return this.vbase2Id;
    }

    public void setVbase2Id(Integer vbase2Id) {
        this.vbase2Id = vbase2Id;
    }

    @Column
    public String getComments() {
        return this.comments;
    }

    public void setComments(String comments) {
        this.comments = comments;
    }




}


