package org.youthnet.debug.domain.core;
// Generated 14-Dec-2009 11:46:32 by Hibernate Tools 3.2.2.GA


import java.util.Set;

import org.youthnet.debug.domain.core.*;
import org.youthnet.debug.domain.core.enums.LocationTypes;
import org.youthnet.debug.domain.core.enums.PublicContactDetailsSource;
import org.youthnet.debug.domain.core.lookups.GeographicalArea;

import javax.persistence.*;

/**
 * PostCodeLocationAddress generated by hbm2java
 */
@Entity
@DiscriminatorValue(value = "PostCodeLocationAddress")
public class PostCodeLocationAddress extends LocationBase implements java.io.Serializable {

    @Column
    private boolean UseCustomAddress;

    @ManyToOne(cascade = CascadeType.ALL, fetch = FetchType.EAGER)
    @JoinColumn(name = "AddressId", columnDefinition = "raw(16)")
    private Address CustomAddress;

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "OrgAddressId", columnDefinition = "raw(16)")
    private OrganisationAddress orgAddress;

    @Column
    private boolean UseForContactDetails;

    public PostCodeLocationAddress() {
        this.setLocationType(LocationTypes.POSTCODE);
    }

    public PostCodeLocationAddress(String DisplayString, Opportunity owner, LocationTypes locationType, ContactDetails contactDetails, ContactDetails publicContactDetails, boolean UseCustomOrgName, String CustomOrgName, PublicContactDetailsSource publicContactDetailsSource, Set<GeographicalArea> geographicalAreas, boolean IsActive, boolean UseCustomAddress, Address CustomAddress, OrganisationAddress orgAddress, boolean UseForContactDetails) {
        super(DisplayString, owner, locationType, contactDetails, publicContactDetails, UseCustomOrgName, CustomOrgName, publicContactDetailsSource, geographicalAreas, IsActive);
        this.UseCustomAddress = UseCustomAddress;
        this.CustomAddress = CustomAddress;
        this.orgAddress = orgAddress;
        this.UseForContactDetails = UseForContactDetails;
    }

    public boolean isUseCustomAddress() {
        return this.UseCustomAddress;
    }

    public void setUseCustomAddress(boolean UseCustomAddress) {
        this.UseCustomAddress = UseCustomAddress;
    }

    public Address getCustomAddress() {
        return this.CustomAddress;
    }

    public void setCustomAddress(Address CustomAddress) {
        this.CustomAddress = CustomAddress;
    }

    public OrganisationAddress getOrgAddress() {
        return this.orgAddress;
    }

    public void setOrgAddress(OrganisationAddress orgAddress) {
        this.orgAddress = orgAddress;
    }

    public boolean isUseForContactDetails() {
        return this.UseForContactDetails;
    }

    public void setUseForContactDetails(boolean UseForContactDetails) {
        this.UseForContactDetails = UseForContactDetails;
    }


}


