package org.youthnet.debug.domain.core;
// Generated 14-Dec-2009 11:46:32 by Hibernate Tools 3.2.2.GA


import org.youthnet.debug.domain.core.lookups.QualityStdsAndAccreditations;
import org.youthnet.debug.domain.core.lookups.QualityStdsAndAccreditationsStatus;

import javax.persistence.*;

/**
 * QualityStdsAccrPolicyEntry generated by hbm2java
 */
@Entity
@DiscriminatorValue(value = "Q")
public class QualityStdsAccrPolicyEntry extends PolicyEntry implements java.io.Serializable {


private QualityStdsAndAccreditations policy;
private QualityStdsAndAccreditationsStatus policyStatus;

    public QualityStdsAccrPolicyEntry() {
    }

    public QualityStdsAccrPolicyEntry(Integer vbase2Id, String comments, QualityStdsAndAccreditations policy, QualityStdsAndAccreditationsStatus policyStatus) {
        super(vbase2Id, comments);        
       this.policy = policy;
       this.policyStatus = policyStatus;
    }
   
    @ManyToOne(targetEntity = org.youthnet.debug.domain.core.lookups.QualityStdsAndAccreditations.class,
            fetch = FetchType.EAGER)
    @JoinColumn(name = "PolicyId", columnDefinition = "raw(16)")
    public QualityStdsAndAccreditations getPolicy() {
        return this.policy;
    }

    public void setPolicy(QualityStdsAndAccreditations policy) {
        this.policy = policy;
    }

    @ManyToOne(targetEntity = org.youthnet.debug.domain.core.lookups.QualityStdsAndAccreditationsStatus.class,
            fetch = FetchType.EAGER)
    @JoinColumn(name = "PolicyStatusId", columnDefinition = "raw(16)")
    public QualityStdsAndAccreditationsStatus getPolicyStatus() {
        return this.policyStatus;
    }

    public void setPolicyStatus(QualityStdsAndAccreditationsStatus policyStatus) {
        this.policyStatus = policyStatus;
    }
}


