package org.youthnet.debug.domain.core;
// Generated 14-Dec-2009 11:46:32 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * QueriesForViews generated by hbm2java
 */
@Entity
@Table(name = "QueriesForViews")
public class QueriesForViews extends GenericDTO implements java.io.Serializable {

    @Column
    private Integer vbase2Id;

    @Column
    private String queryName;

    @Column(length = 2000)
    private String sqlQuery;

    @Column(length = 2000)
    private String hqlQuery;

    public QueriesForViews() {
    }

    public QueriesForViews(Integer vbase2Id, String queryName, String sqlQuery, String hqlQuery) {
        this.vbase2Id = vbase2Id;
        this.queryName = queryName;
        this.sqlQuery = sqlQuery;
        this.hqlQuery = hqlQuery;
    }

    public Integer getVbase2Id() {
        return this.vbase2Id;
    }

    public void setVbase2Id(Integer vbase2Id) {
        this.vbase2Id = vbase2Id;
    }

    public String getQueryName() {
        return this.queryName;
    }

    public void setQueryName(String queryName) {
        this.queryName = queryName;
    }

    public String getSqlQuery() {
        return this.sqlQuery;
    }

    public void setSqlQuery(String sqlQuery) {
        this.sqlQuery = sqlQuery;
    }

    public String getHqlQuery() {
        return this.hqlQuery;
    }

    public void setHqlQuery(String hqlQuery) {
        this.hqlQuery = hqlQuery;
    }
}


