package org.youthnet.debug.domain.core;
// Generated 14-Dec-2009 11:46:32 by Hibernate Tools 3.2.2.GA


import javax.persistence.*;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VolunteerActivityLog generated by hbm2java
 */
@Entity
@Table(name = "VolunteerActivityLogs")
public class VolunteerActivityLog extends GenericDTO implements java.io.Serializable {

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "VolunteerId", columnDefinition = "raw(16)")
    private Volunteer volunteer;

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "ActivityLogId", columnDefinition = "raw(16)")
    @javax.xml.bind.annotation.XmlTransient
    private ActivityLog activityLog;

    public VolunteerActivityLog() {
    }

    public VolunteerActivityLog(Volunteer volunteer, ActivityLog activityLog) {
        this.volunteer = volunteer;
        this.activityLog = activityLog;
    }

    public Volunteer getVolunteer() {
        return this.volunteer;
    }

    public void setVolunteer(Volunteer volunteer) {
        this.volunteer = volunteer;
    }

    public ActivityLog getActivityLog() {
        return this.activityLog;
    }

    public void setActivityLog(ActivityLog activityLog) {
        this.activityLog = activityLog;
    }


}


