package org.youthnet.debug.domain.core;
// Generated 14-Dec-2009 11:46:32 by Hibernate Tools 3.2.2.GA


import org.hibernate.annotations.Cascade;
import org.youthnet.debug.domain.core.lookups.Country;
import org.youthnet.debug.domain.core.lookups.County;

import javax.persistence.*;

/**
 * VolunteerAddress generated by hbm2java
 */
@Entity
@Table(name = "VolunteerAddresses")
@PrimaryKeyJoinColumn(name = "AddressId", columnDefinition = "raw(16)")
public class VolunteerAddress extends org.youthnet.debug.domain.core.Address implements java.io.Serializable {


    private Volunteer contactDetails;
    private String name;
    private boolean isDefaultAddress;
    private boolean active;

    public VolunteerAddress() {
    }


    public VolunteerAddress(String name) {
        this.name = name;
    }

    public VolunteerAddress(Integer vbase2Id, String address1, String address2, String address3, String town, County county, Country country, String PostCode, String Directions, Volunteer contactDetails, String name, boolean isDefaultAddress) {
        super(vbase2Id, address1, address2, address3, town, county, country, PostCode, Directions);
        this.contactDetails = contactDetails;
        this.name = name;
        this.isDefaultAddress = isDefaultAddress;
    }

    @ManyToOne(targetEntity = org.youthnet.debug.domain.core.Volunteer.class,
            fetch = FetchType.EAGER)
    @Cascade(org.hibernate.annotations.CascadeType.SAVE_UPDATE)
    @JoinColumn(name = "VolunteerId", columnDefinition = "raw(16)")
    @javax.xml.bind.annotation.XmlTransient
    public Volunteer getContactDetails() {
        return this.contactDetails;
    }

    public void setContactDetails(Volunteer contactDetails) {
        this.contactDetails = contactDetails;
    }

    @Column(nullable = false)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column
    public boolean isIsDefaultAddress() {
        return this.isDefaultAddress;
    }

    public void setIsDefaultAddress(boolean isDefaultAddress) {
        this.isDefaultAddress = isDefaultAddress;
    }


    @Column
    public boolean isActive() {
        return this.active;
    }

    public void setActive(boolean active) {
        this.active = active;
    }

}


