package org.youthnet.debug.domain.core;
// Generated 14-Dec-2009 11:46:32 by Hibernate Tools 3.2.2.GA


import org.youthnet.debug.domain.core.lookups.TelephoneType;
import org.youthnet.debug.domain.core.old.VolunteerContactInfo;

import javax.persistence.*;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VolunteerContactTelephone generated by hbm2java
 */
@Entity
@Table(name = "VolunteerContactTelephones")
@PrimaryKeyJoinColumn(name = "VolunteerContactInfoId", columnDefinition = "raw(16)")
public class VolunteerContactTelephone extends VolunteerContactInfo implements java.io.Serializable {

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "VolunteerId", columnDefinition = "raw(16)")
    @javax.xml.bind.annotation.XmlTransient
    private Volunteer contactDetails;

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "TelephoneTypeId", columnDefinition = "raw(16)")
    private TelephoneType type;

    @Column(length = 255, nullable = false, name = "tel_number")
    private String number;

    public VolunteerContactTelephone() {
    }


    public VolunteerContactTelephone(String number) {
        this.number = number;
    }

    public VolunteerContactTelephone(boolean isActive, boolean isDefault, String notes, Volunteer contactDetails, TelephoneType type, String number) {
        super(isActive, isDefault, notes);
        this.contactDetails = contactDetails;
        this.type = type;
        this.number = number;
    }

    public Volunteer getContactDetails() {
        return this.contactDetails;
    }

    public void setContactDetails(Volunteer contactDetails) {
        this.contactDetails = contactDetails;
    }

    public TelephoneType getType() {
        return this.type;
    }

    public void setType(TelephoneType type) {
        this.type = type;
    }

    public String getNumber() {
        return this.number;
    }

    public void setNumber(String number) {
        this.number = number;
    }


}


