package org.youthnet.debug.domain.core;
// Generated 14-Dec-2009 11:46:32 by Hibernate Tools 3.2.2.GA


import org.hibernate.annotations.Cascade;
import org.youthnet.debug.domain.core.Address;
import org.youthnet.debug.domain.core.Volunteer;
import org.youthnet.debug.domain.core.lookups.Country;
import org.youthnet.debug.domain.core.lookups.County;

import javax.persistence.*;

/**
 * VolunteerAddress generated by hbm2java
 */
@Entity
@Table(name = "VolunteerAddresses")
@PrimaryKeyJoinColumn(name = "AddressId", columnDefinition = "raw(16)")
public class VolunteerAddress extends Address implements java.io.Serializable {

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "VolunteerId", columnDefinition = "raw(16)")
    @javax.xml.bind.annotation.XmlTransient
    private Volunteer contactDetails;

    @Column(nullable = false)
    private String name;

    @Column
    private boolean isDefaultAddress;

    @Column
    private boolean isActive;

    public VolunteerAddress() {
    }


    public VolunteerAddress(String name) {
        this.name = name;
    }

    public VolunteerAddress(Integer vbase2Id, String address1, String address2, String address3, String town, County county, Country country, String PostCode, String Directions, Volunteer contactDetails, String name, boolean isDefaultAddress) {
        super(vbase2Id, address1, address2, address3, town, county, country, PostCode, Directions);
        this.contactDetails = contactDetails;
        this.name = name;
        this.isDefaultAddress = isDefaultAddress;
    }

    public Volunteer getContactDetails() {
        return this.contactDetails;
    }

    public void setContactDetails(Volunteer contactDetails) {
        this.contactDetails = contactDetails;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public boolean isIsDefaultAddress() {
        return this.isDefaultAddress;
    }

    public void setIsDefaultAddress(boolean isDefaultAddress) {
        this.isDefaultAddress = isDefaultAddress;
    }

    public boolean isIsActive() {
        return this.isActive;
    }

    public void setIsActive(boolean active) {
        this.isActive = active;
    }
}


