package org.youthnet.debug.domain.core;
// Generated 14-Dec-2009 11:46:32 by Hibernate Tools 3.2.2.GA


import org.youthnet.debug.domain.core.Volunteer;
import org.youthnet.debug.domain.core.lookups.EmailType;
import org.youthnet.debug.domain.core.VolunteerContactInfo;

import javax.persistence.*;

/**
 * VolunteerContactEmail generated by hbm2java
 */
@Entity
@Table(name = "VolunteerContactEmails")
@PrimaryKeyJoinColumn(name = "VolunteerContactInfoId", columnDefinition = "raw(16)")
public class VolunteerContactEmail extends VolunteerContactInfo implements java.io.Serializable {

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "VolunteerId", columnDefinition = "raw(16)")
    @javax.xml.bind.annotation.XmlTransient
    private Volunteer contactDetails;

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "TelephoneTypeId", columnDefinition = "raw(16)")
    private EmailType type;

    @Column(length = 320, nullable = false)
    private String email;

    public VolunteerContactEmail() {
    }


    public VolunteerContactEmail(String email) {
        this.email = email;
    }

    public VolunteerContactEmail(boolean isActive, boolean isDefault, String notes, Volunteer contactDetails, EmailType type, String email) {
        super(isActive, isDefault, notes);
        this.contactDetails = contactDetails;
        this.type = type;
        this.email = email;
    }

    public Volunteer getContactDetails() {
        return this.contactDetails;
    }

    public void setContactDetails(Volunteer contactDetails) {
        this.contactDetails = contactDetails;
    }

    public EmailType getType() {
        return this.type;
    }

    public void setType(EmailType type) {
        this.type = type;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }


}


