package org.youthnet.debug.domain.core;
// Generated 14-Dec-2009 11:46:32 by Hibernate Tools 3.2.2.GA


import org.hibernate.annotations.Cascade;
import org.youthnet.debug.domain.core.lookups.EmailType;

import javax.persistence.*;

/**
 * VolunteerContactEmail generated by hbm2java
 */
@Entity
@Table(name = "VolunteerContactEmails")
@PrimaryKeyJoinColumn(name = "VolunteerContactInfoId", columnDefinition = "raw(16)")
public class VolunteerContactEmail extends org.youthnet.debug.domain.core.VolunteerContactInfo implements java.io.Serializable {


private Volunteer contactDetails;
private EmailType type;
private String email;

    public VolunteerContactEmail() {
    }

	
    public VolunteerContactEmail(String email) {
        this.email = email;
    }
    public VolunteerContactEmail(boolean isActive, boolean isDefault, String notes, Volunteer contactDetails, EmailType type, String email) {
        super(isActive, isDefault, notes);        
       this.contactDetails = contactDetails;
       this.type = type;
       this.email = email;
    }

    @ManyToOne(targetEntity = org.youthnet.debug.domain.core.Volunteer.class,
            fetch = FetchType.EAGER)
    @Cascade(org.hibernate.annotations.CascadeType.SAVE_UPDATE)
    @JoinColumn(name = "VolunteerId", columnDefinition = "raw(16)")
    @javax.xml.bind.annotation.XmlTransient
    public Volunteer getContactDetails() {
        return this.contactDetails;
    }

    public void setContactDetails(Volunteer contactDetails) {
        this.contactDetails = contactDetails;
    }

    @ManyToOne(targetEntity = org.youthnet.debug.domain.core.lookups.EmailType.class,
            fetch = FetchType.EAGER)
    @JoinColumn(name = "TelephoneTypeId", columnDefinition = "raw(16)")
    public EmailType getType() {
        return this.type;
    }

    public void setType(EmailType type) {
        this.type = type;
    }

    @Column(length = 320, nullable = false)
    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }




}


