package org.youthnet.debug.domain.core.lookups;
// Generated 14-Dec-2009 11:46:32 by Hibernate Tools 3.2.2.GA


import javax.persistence.DiscriminatorValue;
import javax.persistence.Entity;

import org.hibernate.annotations.Type;
import org.youthnet.debug.domain.common.UuidType;
import org.youthnet.debug.domain.core.GenericDTO;

import javax.persistence.*;

/**
 * LookupBase generated by hbm2java
 */
@Entity
@Table(name = "Lookups")
@Inheritance(strategy = InheritanceType.SINGLE_TABLE)
@DiscriminatorColumn(discriminatorType = DiscriminatorType.STRING,
        length = 50,
        name = "Discriminator")
@DiscriminatorValue(value = "LookupBase")
public class LookupBase extends GenericDTO implements java.io.Serializable {

    @Column
    private Integer vBase2Id;

    @Column(columnDefinition = "raw(16)")
    @Type(type = "org.youthnet.debug.domain.common.impl.UuidTypeImpl")
    private UuidType languageId;

    @Column
    private String value;

    @Column
    private boolean isActive;

    @Column
    private Integer sortOrder;

    @Column
    private boolean isUserEditable;

    @Column(columnDefinition = "raw(16)")
    @Type(type = "org.youthnet.debug.domain.common.impl.UuidTypeImpl")
    private UuidType ownerId;

    public LookupBase() {
    }

    public LookupBase(Integer vBase2Id, UuidType languageId, String value, boolean isActive, Integer sortOrder, boolean isUserEditable, UuidType ownerId) {
        this.vBase2Id = vBase2Id;
        this.languageId = languageId;
        this.value = value;
        this.isActive = isActive;
        this.sortOrder = sortOrder;
        this.isUserEditable = isUserEditable;
        this.ownerId = ownerId;
    }

    public Integer getvBase2Id() {
        return this.vBase2Id;
    }

    public void setvBase2Id(Integer vBase2Id) {
        this.vBase2Id = vBase2Id;
    }

    public UuidType getLanguageId() {
        return this.languageId;
    }

    public void setLanguageId(UuidType languageId) {
        this.languageId = languageId;
    }

    public String getValue() {
        return this.value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    public boolean isIsActive() {
        return this.isActive;
    }

    public void setIsActive(boolean isActive) {
        this.isActive = isActive;
    }

    public Integer getSortOrder() {
        return this.sortOrder;
    }

    public void setSortOrder(Integer sortOrder) {
        this.sortOrder = sortOrder;
    }

    public boolean isIsUserEditable() {
        return this.isUserEditable;
    }

    public void setIsUserEditable(boolean isUserEditable) {
        this.isUserEditable = isUserEditable;
    }

    public UuidType getOwnerId() {
        return this.ownerId;
    }

    public void setOwnerId(UuidType ownerId) {
        this.ownerId = ownerId;
    }
}


