package org.youthnet.debug.domain.core.lookups;
// Generated 14-Dec-2009 11:46:32 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;

import org.youthnet.debug.domain.core.GenericDTO;

/**
 * LookupType generated by hbm2java
 */
@Entity
@Table(name = "LookupTypes")
public class LookupType extends GenericDTO implements java.io.Serializable {


private String value;
private boolean canEdit;
private boolean isVisible;

    public LookupType() {
    }

    public LookupType(String value, boolean canEdit, boolean isVisible) {
       this.value = value;
       this.canEdit = canEdit;
       this.isVisible = isVisible;
    }

    @Column
    public String getValue() {
        return this.value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    @Column
    public boolean isCanEdit() {
        return this.canEdit;
    }

    public void setCanEdit(boolean canEdit) {
        this.canEdit = canEdit;
    }

    @Column
    public boolean isIsVisible() {
        return this.isVisible;
    }

    public void setIsVisible(boolean isVisible) {
        this.isVisible = isVisible;
    }




}


